project_id = "bbxtttigsybxwjrtxasx"

[functions.google-fit]
verify_jwt = true

[functions.ai-recommendations]
verify_jwt = true

[functions.habit-chat]
verify_jwt = true

[functions.habit-automation]
verify_jwt = true

[functions.ai-generate-image]
verify_jwt = true
